### ISSUE TITLE
naming series needs to be set.

### ISSUE THREAD

**Issue by wojosc** [phamos-eu/ProMa#34]
ProMa Checklist will not be created manually. Thus it will need a naming_series so it can auto-create an id for the checklist when beeing created. The same should go for ProMa Checklist Data

We will be using the following structure for this:
<img width="667" alt="grafik" src="https://user-images.githubusercontent.com/22279621/223748283-5b290cee-39eb-4043-a7a9-2e7701ee33bc.png">

**Comment by wojosc** [comment]
naming series of ProMa Checklist Template should be set first. This ID should be used in the naming of ProMa Checklist.

**Comment by wojosc** [comment]
The field "title" represents the naming series and is not visible in mobile app

**Comment by roquegv** [comment]
This is solved by https://github.com/phamos-eu/ProMa/pull/67
