### ISSUE TITLE
merge data from doc field to value in table

### ISSUE THREAD

**Issue by wojosc** [phamos-eu/ProMa#39]
from another docType, we will be pulling data into ProMa Checklist. This data will be on doc-field-level.

We will then wan't to merge this data into a table, that will have a field with a value having the same or similar same to the doc-field mentioned earlier.

I was able to solve this via a script but this does not cover the full need of the solution.

We will need to move the value coming from the doc-field to a code-field in the table in which we have a json structure. The json structure will have will have a field value which needs to be added/replaces with out overwriting other data in that field.

**Comment by wojosc** [comment]
this is the code that I used:

```
frappe.ui.form.on('MyDocType', {
    validate: function(frm) {
        $.each(frm.doc.my_child_table || [], function(i, child) {
            if (child.child_name === 'address') {
                frappe.model.set_value(child.doctype, child.name, 'value_field', frm.doc.address);
            }
            if (child.child_name === 'phone') {
                frappe.model.set_value(child.doctype, child.name, 'value_field', frm.doc.phone);
            }
            if (child.child_name === 'mobil') {
                frappe.model.set_value(child.doctype, child.name, 'value_field', frm.doc.mobil);
            }
            if (child.child_name === 'email') {
                frappe.model.set_value(child.doctype, child.name, 'value_field', frm.doc.email_id);
            }
        });
    }
});
```

results to:
![field to table](https://user-images.githubusercontent.com/22279621/224060335-307d83cd-43e7-4cfd-885d-789d08bd62d2.gif)

**Comment by wojosc** [comment]
In ProMa Checklist this looks like:
![grafik](https://user-images.githubusercontent.com/22279621/224061639-8e78450e-c0a7-4275-95b7-56397e44377e.png)

![grafik](https://user-images.githubusercontent.com/22279621/224061732-ee4986ba-185d-424e-92e9-3395e9ec1f2e.png)

with the target field (value)
![grafik](https://user-images.githubusercontent.com/22279621/224061867-c8f3545a-695f-4413-813c-75b9ba5568f0.png)

**Comment by lajidey-foss** [comment]
Your above script would not work as expected, as you are can't set a code docfield this way.

Things to note is 
- The docfield is a "code" field type 
-  The code field is of type JSON
What needs to be done is get the barest minimum JSON structure template that could represent empty state. This json structure will have a value pair field name 'value' which you can then set in the JSON, now your template can be save in the code field

**Comment by roquegv** [comment]
Check the following pull request: https://github.com/phamos-eu/ProMa/pull/40

**Comment by wojosc** [comment]
List of fields that will be definitally be part of euch "ProMa Item Content"

- [ ] name (might be first name & last name separate)
- [ ] street
- [ ] postalcode
- [ ] city
- [ ] country
- [ ] telefon
- [ ] mobil
- [ ] email

beyond these there might be others. This will be needed to be discussed with the customer in more detail.

**Comment by roquegv** [comment]
Please, check the https://github.com/phamos-eu/ProMa/pull/42 pull request.

**Comment by wojosc** [comment]
Tests have worked. Was shifted to a different model. See ProMa Checklist Mapping
