### ISSUE TITLE
Datamapper from "Project Specific Values" to "ProMa Checklist"

### ISSUE THREAD

**Issue by wojosc** [phamos-eu/ProMa#43]
In the ProMa App we are facing the following challange:

The DocType ProMa Checklist has a table in which all the data is set to create the mobile apps constalation. The constalation a collection of pages, groups and item. Some of the items are extension, behave more or less like items though.

example

```
Page
 Group
   Item
   Item
   Item
  Group
   Item
   Item
   Item
  Page
   Group
    Item
    Item
   Group
   Item
   ...
...
```
the listed fields of the type "item" are dynamic as they are project specific. These project specifics come from different places in our system.

One source is information stored in the Project Contact DocType. Here we will find data like name, telefon, email_id. The DocType Project Address follows the same concept.

We will create a DocType called something like "Project Value Mapping" (yet to be difined). In this doctype we will have a table in which we can chose a DocType in a link field in the first column. In the second column we will be able to fetch any doc-level field found in that doctype. In the third column we will be able to select any of the fields of the type "item" shown above.

It will look something like this
![grafik](https://user-images.githubusercontent.com/22279621/225708465-e5c7c5dd-e4bb-4952-9c22-200806ac6a22.png)

No 1: a Link field to the Doctype from which we wan't to fetch the fields
No 2: a select field to the specific field from No 1 where the values are
No 3: a select field to the target line in which the value from No 2 should be set (line of the table inside of ProMa Checklist)
No 4: an example idea: The ProMa Checklist Template which will be used as the frame where the fields will be defined
No 5: possible other fields which might be relevent for the process. Project maybe?

Here is an example of how the select on the data can look like. The function that we are looking for seems to be already existent in frappe/ERPNext and can maybe be built on. The example is in Web Form Doctype
![grafik](https://user-images.githubusercontent.com/22279621/225712536-98ec9c15-fe27-4866-8114-e0560f9dea29.png)

**Comment by roquegv** [comment]
Another way to put it. Here are the tasks to be done:
* Create a "ProMa Checklist Mapping Template" Doctype, with the following fields:
    - Project (link)
    - ProMa Checklist (link)
    - Mappings (table):
        - Doctype (link)
        - Field (select a field from the list of selected doctype's fields)
        - ProMa Checklist item name (select from the list of items names in the selected ProMa Checklist)
* Fetch all the fields from the selected doctype and show them in the Mapping table above
* Fetch all the "Proma CheckList Content" names, with the item type = Item, and show them in the Mapping table above
* Propose a way in which could be handled the Project Specifics cases (for example, the SM4 in SONNEN)
    - One possible way is to have a field in Sales Order (Purchase Order) that stores the data that will be copied into the ProMa Checklist Content table. In this way we just need to fetch the Sales Order fields within the Mapping Table automatically, show them as a Select and then the user select the correct field (for example: "SM4 modules" in the case of SONNEN). This field would be project specifics, so for each project there would be a field that stores the relevant data and also the function that creates that data.

**Comment by roquegv** [comment]
We will call the mapping doctype as "ProMa Checklist Mapping".

**Comment by roquegv** [comment]
Please, refer to this PR: https://github.com/phamos-eu/ProMa/pull/42#issuecomment-1472762020.

**Comment by wojosc** [comment]
have added some clarifications to field descriptions
![grafik](https://user-images.githubusercontent.com/22279621/225854717-9f654243-9a31-4971-8d90-971a8d55673b.png)

- [ ] Needs to be commited

**Comment by roquegv** [comment]
> have added some clarifications to field descriptions ![grafik](https://user-images.githubusercontent.com/22279621/225854717-9f654243-9a31-4971-8d90-971a8d55673b.png)
> 
>     * [ ]  Needs to be commited

Here is the PR for this: https://github.com/phamos-eu/ProMa/pull/44
