### ISSUE TITLE
client, customer and service partner

### ISSUE THREAD

**Issue by wojosc** [phamos-eu/ProMa#48]
![grafik](https://user-images.githubusercontent.com/22279621/226407941-83a4e297-7af8-4a03-ab29-a6827ca1ae84.png)

we should replace these with standard ERPNext fields.

No. 1 -> Company
No. 2 -> Customer
No. 3 -> Supplier

Please check with @njoguchris if this will break the loading of the mobile app. It has to work there!

**Comment by roquegv** [comment]
See PR https://github.com/phamos-eu/ProMa/pull/50

**Comment by wojosc** [comment]
This also had to be changed in ProMa Checklist Data
