### ISSUE TITLE
Service Partner Bestellungen

### ISSUE THREAD

**Issue by wojosc** [phamos-eu/ProMa#49]
For Purchase Order we have created a custom Report which looks like this
![grafik](https://user-images.githubusercontent.com/22279621/226552613-f6b0bec8-88b0-454c-9157-071c4a6adce4.png)

This Report will be used for the "Service Partner Coordinator" (Role) to assign Purchase Orders to his internal team. The team is made up by "App Users" (yet to be defined) and are often known as "ProMa Assigned User ID" so far.

In a Purchase Order we will find to fields that need to be populated by the Coordinator once the Purchase Order is submitted. These fields are
![grafik](https://user-images.githubusercontent.com/22279621/226553133-ada01355-0974-4796-98b6-0114cfce1f7e.png)

1. ProMa Assigned User IDs which is one (mostly) or more App Users that will have a ProMa Checklist sent to their mobile device.
2. The data and time for which the Coordinator has scheduled the appointment on the Job.

Both 1. and 2. will be transfered to the ProMa Checklist.

To transfer the data we need the coordinator to trigger an action. This action will ask him to fill the values above and submit. When submitting the ProMa Checklist is created and the Purchase Order will change it's status.

For the status we might use the Workflow functionality and a corresponding field.

As an example on how the action could be triggered from the Report view above there is an example on how it's done in Standard frappe/ERPNext in the DocType Todo
![grafik](https://user-images.githubusercontent.com/22279621/226554477-d6588adf-496c-4879-b971-031854449465.png)

Once clicking the button we would expect a dialog to open in which the coordinator will see something like this:
![grafik](https://user-images.githubusercontent.com/22279621/226556026-99e5af7c-32ed-473a-b3c7-1b07d1c6b14a.png)

1. select a date-time
2. select x-amount of users
3. check-box for agreeing to terms
4. Button to Submit.

No 3. is mostly used to hint the user, that when submitting there will be a ProMa Checklist created and the data will be booked sent to our system. This could also be done with a further pop-up saying "Are you sure... (Yes/No)"

Example:
![grafik](https://user-images.githubusercontent.com/22279621/226558783-fe3fc516-13f0-4c97-a193-79ad181ade55.png)

**Comment by roquegv** [comment]
Tasks:

- [ ] Create the report
- [ ] Add the button to the report
- [ ] Create the dialog popup with the fields
- [ ] Show the confirmation dialog before proceed
- [ ] Copy the data from the dialog to the Purchase Order
