### ISSUE TITLE
Make the mapping process more generic

### ISSUE THREAD

**Issue by roquegv** [phamos-eu/ProMa#59]
The mapping process for now only works for creation of Proma Checklist from a Purchase Order.
The limitation is that it only takes into account the following doctypes: Project Contact, Project Address and the Purchase Order itself. That is, there are fields inside Purchase Order to reference Project Contact and Project Address, so we can take the values from this referenced documents.

We will need to consider the following doctypes links:
- Project Contact
- Project Address
- SONNEN Work Order
- SONNEN Asset
- Project

Specific tasks:
- [x] Add a link field for SONNEN Work Order into Purchase Order.
- [x] Consider the SONNEN Work Order during the mapping process (take the values from the SONNEN Work Order reference).
- [x] During the mapping process, take the values from the Project referenced in the Purchase Order.
- [x] Add a link field for SONNEN Asset into Purchase Order.
- [x] Think of a generic way in which any link field inside Purchase Order could be considered during the mapping process.

**Comment by wojosc** [comment]
![grafik](https://user-images.githubusercontent.com/22279621/226907760-e9d68aeb-6621-4a77-8541-5a661eaf24c6.png)

**Comment by roquegv** [comment]
>  Think of a generic way in which any link field inside Purchase Order could be considered during the mapping process.

This could be done in the following way: if inside Proma Checklist Mapping table there is, for example, "SONNEN Work Order" as a source doctype, then we can assume that there is a link field called "sonnen_work_order" in Purchase Order that references to a SONNEN Work Order document. In that case, we could just do `source_doctype.lower().replace(" ", "_")` to get the fieldname for that link field. With that fieldname we can get the value of that field and with this value we can fetch the data for that document.

**Comment by wojosc** [comment]
> The mapping process for now only works for creation of Proma Checklist from a Purchase Order. The limitation is that it only takes into account the following doctypes: Project Contact, Project Address and the Purchase Order itself. That is, there are fields inside Purchase Order to reference Project Contact and Project Address, so we can take the values from this referenced documents.
> 
> We will need to consider the following doctypes links:
> 
>     * Project Contact
> 
>     * Project Address
> 
>     * SONNEN Work Order
> 
>     * SONNEN Asset
> 
>     * Project
> 
> 
> Specific tasks:
> 
>     * [x]  Add a link field for SONNEN Work Order into Purchase Order.
> 
>     * [x]  Consider the SONNEN Work Order during the mapping process (take the values from the SONNEN Work Order reference).
> 
>     * [x]  During the mapping process, take the values from the Project referenced in the Purchase Order.
> 
>     * [x]  Add a link field for SONNEN Asset into Purchase Order.
> 
>     * [x]  Think of a generic way in which any link field inside Purchase Order could be considered during the mapping process.

Hey Roque,

there are some points here which I am not sure about. I see, you have the SONNEN Asset and the Project to be DocTypes that need to be considered. SONNEN Asset for example is a doctype that we are not really using in our scenario.

I'm unsure why we would need some of these links the Purchase Order, as we are trying to minimize links between the SONNEN DocTypes and the generic ERPNext DocTypes.

Best we have a quick chat over this later today to clear things up. Thank you.

**Comment by roquegv** [comment]
> I'm unsure why we would need some of these links the Purchase Order, as we are trying to minimize links between the SONNEN DocTypes and the generic ERPNext DocTypes.

It is already removed by https://github.com/suncycle-eu/suncycle/pull/5
