### ISSUE TITLE
Finalizing

### ISSUE THREAD

**Issue by wojosc** [phamos-eu/ProMa#60]
SONNEN Work Order

- [x] Priority wird durch sonnen API geliefert
- [x] change priority field-type to data and remove options
- [x] add sonnen_asset_id
- [x] https://github.com/suncycle-eu/SONNEN-API/pull/36

SONNEN Address

- [x] delete field "sonnen_id"
- [x] change naming to auto-naming
- [x] https://github.com/suncycle-eu/SONNEN-API/pull/37

SONNEN Contact

- [x] Info on e-mail
- [x] Info on mobile
- [x] INfo on phone

Sales Order
All good
Purchase Order

- [x] Links to Contact and Address not being transfered. Quations: How does the Mapping identify which contact and which address? -> not sure where error was. Seems to work.

- [x] Assignes User IDs -> allow after submit

- [x] external_id present -> field was replaced by reference_id through out the system.

Webhook

- [x] Webhook from ERPNext does not trigger on change of Purchase Order -> needs testing

ProMa Checklist Mapping

- [x] Has to be able to cover SONNEN Work Order
- [x] Has to be able to cover fiedltype "datetime"

ProMa Checklist 

- [x] external_id present -> field was replaced by reference_id through out the system.
- [x] external_id needs to be passed via the script -> field was replaced by reference_id through out the system.

ProMa Checklist Data

- [x] external_id present -> field was replaced by reference_id through out the system.
- [x] external_id needs to be passed via the script -> field was replaced by reference_id through out the system.

Extensions
- [x] 		Serials = Values field -> Name
- [x] 		Description = Text area field -> Name

- [x] PDF can be pulled
- [x] PDF Standard Print needs to be identified for now the Print Format must carry the name "ProMa Checklist Data 0"

Schedule Job Type

- [x] #62

**Comment by roquegv** [comment]
I can do the tasks for:
- SONNEN Contact
- Purchase Order
- ProMa Checklist Mapping
- ProMa Checklist

**Comment by roquegv** [comment]
> Links to Contact and Address not being transfered. 

I changed the server script in https://sonnen-api.frappe.cloud to include the project_contact, project_address and customer_reference data.

> How does the Mapping identify which contact and which address?

The mapping process assumes that the link field (to a Project Contact document, for example) is present in the Purchase Order, so it has the reference to that document and read the values in there.

**Comment by roquegv** [comment]
New set of tasks:

- [ ] make suggestion for solving the issue with the condition on the webhook
- [x] review the PRs from SONNEN and merge (if good)
- [x] search for the SM4 item in the SONNEN Work Order and set the quantity to the new anzahl_sm4 field
- [ ] Use the anzahl_sm4 in the mapping process

**Comment by roquegv** [comment]
>  Webhoof from ERPNext does not trigger on change of Purchase Order -> needs testing

Now the condition is set to `doc.workflow_state=="ProMa"`. Maybe you can try to look at the `scheduled_date` as was the previous approach, like this: `doc.scheduled_date != ""`.

**Comment by roquegv** [comment]
New tasks:

- [ ] add SONNEN Case Number as a field in the SONNEN Work Order
- [ ] replace external_id with reference_id in every doctype that has it, this reference_id should be equals to SONNEN case number
- [ ] Hint field in Proma Checklist Content and Proma Checklist Data should be "small text" and translatable
- [ ] Check the problem with the mapping from SONNEN Address to Project Address (and Contact)

**Comment by roquegv** [comment]
> Check the problem with the mapping from SONNEN Address to Project Address (and Contact)

No problem found for this.

Here are the evidences:
- SONNEN Work Order: https://sonnen-api.frappe.cloud/app/sonnen-work-order/0WO1X000001BgVZWA0
- Sales Order: https://sonnen-api.frappe.cloud/app/sales-order/SAL-ORD-2023-00026 (external_id = 0WO1X000001BgVZWA0)
- Purchase Order: https://sonnen-api.frappe.cloud/app/purchase-order/PUR-ORD-2023-00010 (external_id = 0WO1X000001BgVZWA0)
- Project Address: https://sonnen-api.frappe.cloud/app/project-address/155eb01c58 (for purchase order PUR-ORD-2023-00010): this address has "Steenklippen 9" 	as Address Line 1.
- There are 2 Proma Checklist for this external_id: https://sonnen-api.frappe.cloud/app/proma-checklist/Sonnen%20Batteriemodultausch%20V1.5CL02984 and https://sonnen-api.frappe.cloud/app/proma-checklist/Sonnen%20Batteriemodultausch%20V1.5CL02986, both of them have "Steenklippen 9" as "Straße und Hausnummer" inside Proma Checklist Content table.

This is for the case 0WO1X000001BgVZWA0. The same applies to the 0WO1X000001BhxpWAC case. For the other cases (SONNEN Work Order) no associated Purchase Order were found, so no Proma Checklist neither.

So, I can conclude, with high degree of certainty, that that there is no problem with the mapping process.

**Comment by roquegv** [comment]
Any update on "ProMa Checklist Data"?
This is the only task group that is not fully marked as done.

**Comment by roquegv** [comment]
All tasks done.
Closing.
