### ISSUE TITLE
Job fetching finished data is running into an error

### ISSUE THREAD

**Issue by njoguchris** [phamos-eu/ProMa#62]
The playback data running into error has been solved using this PR #58

**Comment by wojosc** [comment]
@njoguchris on this we do have to save the "Playback Settings" every time we do an update not to run in that other problem.

Can we clean up that doctype and merge it into the ProMa Settings?
Also the code in that Doctype could be made more neet in maybe seperate fields?

**Comment by roquegv** [comment]
Any update on this?

**Comment by wojosc** [comment]
> Any update on this?

as discussed yesterady we will move the settings into the DocType "ProMa Settings". Also it might be helpful to put all the configurations in seperate fields in the settings to make it more user friendly. This will only make sense though if it solves the fact that we have to re-save the Settings everytime we do an update of the system.

@njoguchris is that all correct?

**Comment by njoguchris** [comment]
The issue of resaving comes due to the file content being deleted on update. 

The configurations are usually given as a json and I deem it best to add them as a dictionary and not one by one. 

If we insist they can be changed to one field each. Meaning our document will have like 12 extra fields and in a situation a new entry is done the field has to be added unlike in a json you do not need an extra field. 

My thinking a hack would be adding the values after install but again since it's sensitive information shouldn't be seen anywhere on the code

**Comment by wojosc** [comment]
thank you for your input. What I would like to avoid is having to have to remember to "refresh" the page after every update of the system. This is something that needs human action after install which seems very unnecessary.

If, putting each line into a seperate fields solves this, then I guess it would be a good way to do that. If putting it into around 12 fields and then needed to refresh 12 fields then it is more complicated to to and not feasable.

Looking forward to further ideas

**Comment by njoguchris** [comment]
A solution is we can do a after_install hook to check if the field has a value and it saves to the file.

**Comment by wojosc** [comment]
thanks for the input. To technical for me to be able to answer. Please discuss with  @roquegv to find a good solution.

**Comment by njoguchris** [comment]
This was resolved by #81
