### ISSUE TITLE
Active ProMa Checklist Mapping

### ISSUE THREAD

**Issue by wojosc** [phamos-eu/ProMa#87]
To have the custom values in ProMa Checklist we need to link a ProMa Checklist Mapping in Project. To clean this up and make sure, that less errors happen we should do the following:

- [x] Make ProMa Checklist Mapping Submittable so it can not be changed by accident
- [x] Add "Is Active" Button to ProMa Checklist Mapping. This button shall set the Mapping in the linked Project.

**Comment by roquegv** [comment]
ok, I'll do this

**Comment by wojosc** [comment]
I suggest we set up a dev system in which we can test with clean data...does that make sense?

**Comment by roquegv** [comment]
> I suggest we set up a dev system in which we can test with clean data...does that make sense?

If there isn't any such dev system, then it is a good idea to have one.

**Comment by roquegv** [comment]
Solved by https://github.com/phamos-eu/ProMa/pull/94
