### ISSUE TITLE
Users not assigned when manually triggering checklist

### ISSUE THREAD

**Issue by wojosc** [phamos-eu/ProMa#91]
When hitting this button Users are not assigned!

![grafik](https://user-images.githubusercontent.com/22279621/231115680-b0d98408-5f93-45f2-a55f-ee2fe2e63dec.png)

**Comment by wojosc** [comment]
this was due to an old field that was deprecated. The field: assigned_users_ids has been removed. The correct field assigned_user_ids was set to "allow after submit"

**Comment by roquegv** [comment]
Is this solved then?

**Comment by wojosc** [comment]
> Is this solved then?

when we push the linked PR it should be solved. Yes.
