### ISSUE TITLE
Asset ID not being pulled when SONNEN Work Order created

### ISSUE THREAD

**Issue by wojosc** [phamos-eu/ProMa#93]
it seems, that the asset id in SONNEN work order is not set when it is created via API.

![grafik](https://user-images.githubusercontent.com/22279621/231183111-00bf86db-ac4e-4614-9cd6-ad8bbc42b8f6.png)

The asset id is needed on the ProMa Checklist and needs to exist on SONNEN Work Order when this is created.

**Comment by roquegv** [comment]
Solving this in https://github.com/suncycle-eu/SONNEN-API/pull/48
