### ISSUE TITLE
Link ProMa User ID to Supplier

### ISSUE THREAD

**Issue by wojosc** [phamos-eu/ProMa#95]
ProMa User ID should have a link to a Supplier

**Comment by roquegv** [comment]
Solved by https://github.com/phamos-eu/ProMa/pull/94/commits/cd4b51d5d4f3a5954ad573036d0736c7e8d6417d

**Comment by wojosc** [comment]
will need to remember to remove the custom field when updating!
![grafik](https://user-images.githubusercontent.com/22279621/234938413-117490cb-ecd6-462b-ad0c-9fbb246bbc4c.png)
