### ISSUE TITLE
Fix Name of ProMa Item Template

### ISSUE THREAD

**Issue by wojosc** [phamos-eu/ProMa#97]
Doctype Proma Item Template should have name "ProMa Item Template"

Check for dependencies in code befor merging!!

**Comment by roquegv** [comment]
Included in https://github.com/phamos-eu/ProMa/pull/94
Commit https://github.com/phamos-eu/ProMa/pull/94/commits/b4f5a2c70d3252699f3a11ccc1006859b4301efd
